const iconList = [
  { emoji: '👩🏻‍🦰', label: 'Woman with Red Hair', value: 0 },
  { emoji: '🧑🏻‍🦰', label: 'Person with Red Hair', value: 1 },
  { emoji: '👵🏻', label: 'Old Woman', value: 2 },
  { emoji: '👴🏻', label: 'Old Man', value: 3 },
  { emoji: '🧛🏻', label: 'Dracula', value: 4 },
  { emoji: '🐶', label: 'Dog', value: 5 },
  { emoji: '🐰', label: 'Rabbit', value: 6 },
  { emoji: '🦊', label: 'Fox', value: 7 },
  { emoji: '🐻', label: 'Bear', value: 8 },
  { emoji: '🐼', label: 'Panda', value: 9 },
  { emoji: '🦁', label: 'Lion', value: 10 },
  { emoji: '🐮', label: 'Cow', value: 11 },
  { emoji: '🐷', label: 'Pig', value: 12 },
  { emoji: '🐸', label: 'Frog', value: 13 },
  { emoji: '🐒', label: 'Monkey', value: 14 },
  { emoji: '🐔', label: 'Chicken', value: 15 },
  { emoji: '🦆', label: 'Duck', value: 16 },
  { emoji: '🐝', label: 'Bee', value: 17 },
  { emoji: '🦄', label: 'Unicorn', value: 18 },
  { emoji: '💰', label: 'Money', value: 19 },
];
